package io.github.martinschneider.orzo.tests;

public class BasicTypeCasts {
  public static void main(String[] args) {
    char chr = (char) 1;
    System.out.println(64 * chr);
    System.out.println((short) chr);
    System.out.println((int) chr);
    System.out.println((long) chr);
    System.out.println((double) chr);
    System.out.println((float) chr);
    byte b = 65;
    System.out.println((byte) b);
    System.out.println((char) b);
    System.out.println((short) b);
    System.out.println((int) b);
    System.out.println((long) b);
    System.out.println((double) b);
    System.out.println((float) b);
    short s = 66;
    System.out.println((byte) s);
    System.out.println((char) s);
    System.out.println((short) s);
    System.out.println((int) s);
    System.out.println((long) s);
    System.out.println((double) s);
    System.out.println((float) s);
    int i = 67;
    System.out.println((byte) i);
    System.out.println((char) i);
    System.out.println((short) i);
    System.out.println((int) i);
    System.out.println((long) i);
    System.out.println((double) i);
    System.out.println((float) i);
    long l = 68;
    System.out.println((byte) l);
    System.out.println((char) l);
    System.out.println((short) l);
    System.out.println((int) l);
    System.out.println((long) l);
    System.out.println((double) l);
    System.out.println((float) l);
    float f = 69;
    System.out.println((byte) f);
    System.out.println((char) f);
    System.out.println((short) f);
    System.out.println((int) f);
    System.out.println((long) f);
    System.out.println((double) f);
    System.out.println((float) f);
    double d = 70;
    System.out.println((byte) d);
    System.out.println((char) d);
    System.out.println((short) d);
    System.out.println((int) d);
    System.out.println((long) d);
    System.out.println((double) d);
    System.out.println((float) d);
    char chr = 'G';
    System.out.println((byte) chr);
    System.out.println((char) chr);
    System.out.println((short) chr);
    System.out.println((int) chr);
    System.out.println((long) chr);
    System.out.println((double) chr);
    System.out.println((float) chr);
  }
}
